project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Exercises/Hands-on_Ex1/Hands-on_Ex1.qmd
          - text: Hands-on Exercise 1 Continued
            href: Hands-on_Exercises/Hands-on_Ex1/Hands-on_Ex1-ctd.qmd
          - text: Hands-on Exercise 2-1
            href: Hands-on_Exercises/Hands-on_Ex2/Hands-on_Ex2-1.qmd
          - text: Hands-on Exercise 2-2
            href: Hands-on_Exercises/Hands-on_Ex2/Hands-on_Ex2-2.qmd
          - text: Hands-on Exercise 2-3
            href: Hands-on_Exercises/Hands-on_Ex2/Hands-on_Ex2-3.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Exercises/Hands-on_Ex3/Hands-on_Ex3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Exercises/Hands-on_Ex4/Hands-on_Ex4.qmd
      - text: In-class Exercises
        menu: 
          - text: In-class_Exercise 1
            href: In-class_Exercises/In-class_Ex1/In-class_Ex1.qmd
          - text: In-class_Exercise 2
            href: In-class_Exercises/In-class_Ex2/In-class_Ex2.qmd
          - text: In-class_Exercise 3
            href: In-class_Exercises/In-class_Ex3/In-class_Ex3.qmd
      - text: Take-home_Exercises
        menu: 
          - text: Take-home_Exercise 1
            href: Take_home_Exercises/Take_home_Ex1/Take-home_Ex1.qmd

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

